name: LMS Lyrion Music Server(Formerly Logitech Media Server)
version: 8.5.2.0
slug: lms
description: LMS Lyrion Music Server, Formerly the Logitech Media Server & SqueezeBox Server
  Server & UPNP Music Server
url: https://github.com/pssc/ha-addon-lms/lms/
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
audio: true
stdin: true
init: false
ports:
  9000/tcp: 9000
  9090/tcp: 9090
  3483/tcp: 3483
  3483/udp: 3483
ports_description:
  9000/tcp: Web and json API Access
  9090/tcp: CLI Access
  3483/tcp: Slimserver Protocol for players
  3483/udp: Slimserver Protocol for players
timeout: 180
map:
  - config:rw
  - ssl
  - share:rw
  - backup:rw
  - media:rw
image: ghcr.io/pssc/ha-addon-lms-{arch}
tmpfs: true
hassio_api: true
apparmor: false
udev: true
full_access: true
homeassistant_api: true
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
host_network: true
backup_exclude:
  - ./lms/music/**
  - ./lms/mnt/**
  - ./lms/notbackedup/**
  - ./lms/test/*
  - '*/nobackup/*'
services:
  - mqtt:want
ingress: true
ingress_port: 0
panel_icon: mdi:music-box
panel_title: LMS
panel_admin: false
stage: experimental
options:
  links: []
  mounts: []
  dirs: []
  init_commands: []
  packages: []
schema:
  skin: str?
  ssl: bool?
  certfile: str?
  keyfile: str?
  tmpfs: bool?
  mount: str?
  options: str?
  logdir: str?
  logfile: str?
  prefs: str?
  cache: str?
  plugs: str?
  saved: bool?
  links:
    - link: str
      dest: str
  mounts:
    - str?
  dirs:
    - str?
  init_commands:
    - str?
  packages:
    - str?
  set_permissions: bool?
  upgrade_packages: bool?
  autoupdate_notify: bool?
